Homework2.2
KristianK1/android-vjestina-tmdb pull request #4
Opened 2022-11-24 15:41 UTC by KristianK1

2022-11-28 16:02 UTC, matejsalkovic reviewed
Well done homework in general.
Most of the comments regarding formatting, hardcoded strings and some bad practices should be fixed in all places, although not mentioned on all of them. So please don't look only at what is commented, but try to find and fix those mistakes on all other places as well.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/model/MovieCategory.kt
> +}
Each file should have empty line at the end. Please find in settings where to enable this.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    Image(painter = painterResource(id = if (state) R.drawable.full_heart else R.drawable.empty_heart),
Why this change?

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +}
Here you should also be able to remove movie from favorites by clicking favorite button. You can have empty implementation here, but `FavoritesScreen` should have it passed in.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +        }) { movie ->
Formatting, if any parameter is split into multiple lines, then rather put each parameter into separate line also.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +        return FavoritesViewState(list)
In Kotlin it is bad practice to create new mutable lists by yourself. Instead of that, you should use `map`, `filter` and other operators to create new lists that way. Here single `map` should be used.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            if (category.itemId in 0..3)
You can use `when` instead of multiple if-else

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            categoryName = "What's popular",
Put strings into strings.xml file and get them from resources.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        val movieCategoriesViewStates = mutableListOf<MovieCategoryLabelViewState>()
Replace with `map` operator as explained before.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember { mutableStateOf(navController.currentDestination == null) }
Instead of manually changing this state, you can derive it from `navBackStackEntry?.destination?.route` by comparing it with routes that should have bottom bar. Use `derivedStateOf`.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    Image(painter = painterResource(
Try to explore difference between `Image` and `Icon` in compose, and use later where applicable.

2022-11-28 16:02 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                },
Pass this click to the caller, try to implement as much as you can without the ViewModel, and handle everything in route function.

2022-11-28 16:04 UTC, matejsalkovic requested changes
Forgot to request changes by accident.

2022-12-01 05:29 UTC, KristianK1 commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    Image(painter = painterResource(id = if (state) R.drawable.full_heart else R.drawable.empty_heart),
incorrect auto-formatting settings

2022-12-01 06:37 UTC, KristianK1 commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                },
not sure what do you mean, but i did something

2022-12-08 11:09 UTC, pero18 requested changes
There are still too many mistakes to approve this homework. 

There isn't empty line at the end of each file (as Matej requested, it was also requested on the first homework)
Code is commented instead of deleted
Back button doesn't have proper padding and is glued to the end of the screen
All used dimensions should be in dimens file instead of hardcoding it
Magic number
Modifier is passed but not used in a lot of places
You emit multiple composables from function `MovieOverview` not sure if that is the only place ( you should always emit single composable for example some Compose layout like `Box `or `Column` or `Row`... which can have content with more then 1 composable

Please fix everything mentioned, if you have any troubles please ask for help.

2022-12-12 10:09 UTC, pero18 approved these changes
Well done, after you merge this, please rebase homework3 to dev so that Hw3 PR doesn't have changes from HW2 in it. 
After you are done you can add me as a reviewer.

2022-12-12 10:14 UTC, merged