Homework4
KristianK1/android-vjestina-tmdb pull request #6
Opened 2022-12-20 10:48 UTC by KristianK1

2022-12-22 13:00 UTC, pero18 requested changes
Application looks great! The homework is well written. 
On movieDetails screen rating component doesn't render correctly. 
You could easily solve this by formatting number to only show 1 or 2 decimals but try to do it inside the component (you don't have to scale the text just use overflow if it is too large).

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/database/FavoriteMovieDao.kt
> +    fun removeFavorites(id: Int)
One-shot operations on a database or server should be suspending!
Also since you are adding and removing a single element more appropriate names would be `addFavorite` and `removeFavorite`

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/di/databaseModule.kt
> +    }
I suggest that you remove the function and just put the code of the function on call site. 
So instead of : 
```
single{
        provideFavoriteMovieDao(get())
    }
```

You would have 
```
single{
        provideFavoriteMovieDao(get().getMovieDao())
    }
```

You can leave it as is if you like it but I usually avoid declaring functions inside another functions, because to use them they have to be declared before they are used. Also, function is supposed to do one thing (SRP), but since this function just calls another function it is a bit redundant, it doesn't extract any logic. 
Hope this makes more sense, if you wish we could further discuss this.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/network/MovieServiceImpl.kt
> +//        if (httpResponse.status.value in 200..299) {
remove unnecessary comments.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/network/model/MovieDetailsResponse.kt
> +    val voteAverage: Float, //was double
remove comment

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/network/model/MovieDetailsResponse.kt
> +                )
Move mapping to  ApiCrewman, every `Api` object should know how to map itself to domain. 
The current implementation breaks SRP, because the class can change for 3 reasons (instead for one) -> if `Crewman` changes, if `Actor` changes and if `MovieDetails` changes.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/repository/MovieRepositoryImpl.kt
> +                    MovieCategory.POPULAR_STREAMING -> {
Not sure what did you set for maxLineSize in Android, but if possible do it like this: 
`MovieCategory.POPULAR_STREAMING -> movieService.fetchPopularMovies()
`it just looks much nicer and more compact.  This is just my personal preference, so you don't have to do it if you disagree.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/network/MovieService.kt
> +    suspend fun fetchTopRatedMovies(): MovieResponse?
Why did you change the contract and made the return type nullable?

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/repository/MovieRepositoryImpl.kt
> +                emit(movieResponse!!.movies) //TODO remove !!
`movieResponse` shouldn't be nullable. Also always check that there are no unnecessary TODO-s ( TODO-s are almost always unnecessary  because they are rarely fixed once the code is merged in dev )

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/repository/MovieRepositoryImpl.kt
> +    override suspend fun addMovieToFavorites(movieId: Int, posterUrl: String) {
You changed the contract and now the caller has to pass ImageUrl along with movieId, but it should be the repositories responsibility to get image from movieId. 
Remove that argument and see if you really need movie in t`oggleFavorites` method.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/repository/MovieRepositoryImpl.kt
> +            else addMovieToFavorites(movieId, movie.imageUrl!!)
You are using `!!` too much it should almost never be used in kotlin. 
If you have to use it odds are that you are doing something wrong. 
In this case we want to save movie to details even when imageUrl is null, just transform it to blank `String`.

2022-12-22 13:00 UTC, pero18 commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/Crewmanitem.kt
> +//}
I suggest reading chapter 4 from [https://thixalongmy.haugiang.gov.vn/media/1175/clean_code.pdf](Clean code) because you abuse comments.

2022-12-23 01:11 UTC, KristianK1 commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/Crewmanitem.kt
> +//}
Will do.

2022-12-23 01:11 UTC, KristianK1 commented on app/src/main/java/agency/five/codebase/android/movieapp/data/repository/MovieRepositoryImpl.kt
> +            else addMovieToFavorites(movieId, movie.imageUrl!!)
I just left it in one place

2022-12-28 15:36 UTC, pero18 approved these changes

2022-12-30 15:25 UTC, merged